In [139]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [140]:
from pandas import Series, DataFrame

In [141]:
obj = pd.Series([4, 7, -5, 3])

In [142]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [143]:
obj.values

array([ 4,  7, -5,  3])

In [144]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [145]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [146]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [147]:
obj2.values

array([ 4,  7, -5,  3])

In [148]:
obj2['a']

-5

In [149]:
obj2['d'] = 6

In [150]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [151]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [152]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [153]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [154]:
'b' in obj2

True

In [155]:
'e' in obj2

False

In [156]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [157]:
obj3 = pd.Series(sdata)

In [158]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [159]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [160]:
obj4 = pd.Series(sdata, index=states)

In [161]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [162]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [163]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [164]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [165]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [166]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [167]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [168]:
obj4.name = 'population'

In [169]:
obj4.index.name = 'state'

In [170]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [171]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [172]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [173]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [174]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

In [175]:
frame = pd.DataFrame(data)

In [176]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [177]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [178]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [179]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [180]:
frame2 = pd.DataFrame(data, columns=['year','state','pop','debt'], index=['one','two','three','four','five','six'])

In [181]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [182]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [183]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [184]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [185]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [186]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [187]:
frame2['debt'] = 16.5

In [188]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [189]:
frame2['debt'] = np.arange(6.)

In [190]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [191]:
frame2['index'] = np.arange(len(frame2))

In [192]:
frame2

year   state  pop  debt  index
one    2000    Ohio  1.5   0.0      0
two    2001    Ohio  1.7   1.0      1
three  2002    Ohio  3.6   2.0      2
four   2001  Nevada  2.4   3.0      3
five   2002  Nevada  2.9   4.0      4
six    2003  Nevada  3.2   5.0      5

In [193]:
frame2.set_index(np.arange(len(frame2)), inplace=True)

In [194]:
frame2

year   state  pop  debt  index
0  2000    Ohio  1.5   0.0      0
1  2001    Ohio  1.7   1.0      1
2  2002    Ohio  3.6   2.0      2
3  2001  Nevada  2.4   3.0      3
4  2002  Nevada  2.9   4.0      4
5  2003  Nevada  3.2   5.0      5

In [195]:
frame2.drop('index', axis=1, inplace=True)

In [196]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [197]:
frame2['index'] = ['one','two','three','four','five','six']

In [198]:
frame2

year   state  pop  debt  index
0  2000    Ohio  1.5   0.0    one
1  2001    Ohio  1.7   1.0    two
2  2002    Ohio  3.6   2.0  three
3  2001  Nevada  2.4   3.0   four
4  2002  Nevada  2.9   4.0   five
5  2003  Nevada  3.2   5.0    six

In [199]:
frame2.set_index('index', inplace=True)

In [200]:
frame2

year   state  pop  debt
index                         
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [201]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [202]:
frame2['debt'] = val

In [203]:
frame2.rename_axis(None, inplace=True)

In [204]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [205]:
frame2['eastern'] = frame2.state == 'Ohio'

In [206]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [207]:
del frame2['eastern']

In [208]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [209]:
pop = {
    'Nevada': {2001: 2.4, 2002: 2.9},
    'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6},
}

In [210]:
frame3 = pd.DataFrame(pop)

In [211]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [212]:
frame3.sort_index()

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [213]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [214]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [215]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [216]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [217]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [218]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [219]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [220]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [221]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [222]:
index = obj.index

In [223]:
index

Index(['a', 'b', 'c'], dtype='object')

In [224]:
index[1:]

Index(['b', 'c'], dtype='object')

In [225]:
labels = pd.Index(np.arange(3))

In [226]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [227]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [228]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [229]:
obj2.index is labels

True

In [230]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [231]:
frame3.sort_index(inplace=True)

In [232]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [233]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [234]:
'Ohio' in frame3.columns

True

In [235]:
2003 in frame3.index

False

In [236]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [237]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [238]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d','b','a','c'])

In [239]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [240]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [241]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [242]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])

In [243]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [244]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [245]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), 
                    index=['a','c','d'],
                    columns=['Ohio', 'Texas', 'California'])

In [246]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [247]:
frame2 = frame.reindex(['a','b','c','d'])

In [248]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [249]:
states = ['Texas', 'Utah', 'California']

In [250]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [251]:
obj = pd.Series(np.arange(5.), index=['a','b', 'c','d','e'])

In [252]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [253]:
new_obj = obj.drop('c')

In [254]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [255]:
obj.drop(['d', 'e'])

a    0.0
b    1.0
c    2.0
dtype: float64

In [256]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [257]:
# obj.drop(['d','e'], inplace=True)

In [258]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [259]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one','two','three','four'])

In [260]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [261]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [263]:
data.drop(['two'], axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [264]:
obj.drop('c', inplace=True)

In [265]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [266]:
obj = pd.Series(np.arange(4), index=['a','b','c','d'])

In [267]:
obj

a    0
b    1
c    2
d    3
dtype: int64

In [269]:
obj['b']

1

In [270]:
obj[1]

1

In [271]:
obj[2:4]

c    2
d    3
dtype: int64

In [272]:
obj[['b','a','d']]

b    1
a    0
d    3
dtype: int64

In [273]:
obj[[1, 3]]

b    1
d    3
dtype: int64

In [274]:
obj[obj < 2]

a    0
b    1
dtype: int64

In [275]:
obj['b':'c']

b    1
c    2
dtype: int64

In [276]:
obj['b':'c'] = 5

In [277]:
obj

a    0
b    5
c    5
d    3
dtype: int64

In [278]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [279]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [280]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [281]:
data[['two']]

two
Ohio        1
Colorado    5
Utah        9
New York   13

In [282]:
data[['two','three']]

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [283]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [284]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [285]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [286]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [287]:
data[data < 5] = 0

In [288]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [289]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [290]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [291]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [292]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [293]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [294]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [296]:
ser = pd.Series(np.arange(3.))

In [297]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [299]:
# ser[-1]

In [300]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [301]:
ser2[-1]

2.0

In [302]:
ser[:1]

0    0.0
dtype: float64

In [303]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [304]:
ser.iloc[:1]

0    0.0
dtype: float64

In [305]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [307]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
              index=['a', 'c', 'e', 'f', 'g'])

In [308]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [309]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [310]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [315]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                  index=['Ohio', 'Texas', 'Colordao'])

In [316]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [317]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colordao  6.0  7.0  8.0

In [318]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [319]:
df1 + df2

b   c     d   e
Colordao  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [320]:
df1 = pd.DataFrame({'A': [1, 2]})

In [321]:
df2 = pd.DataFrame({'B': [3, 4]})

In [322]:
df1

A
0  1
1  2

In [323]:
df2

B
0  3
1  4

In [324]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [325]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), 
                  columns=list('abcd'))

In [326]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns=list('abcde'))

In [327]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [328]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [329]:
df2.loc[1, 'b'] = np.nan

In [330]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [331]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [332]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [333]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [334]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [335]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [336]:
arr = np.arange(12.).reshape((3, 4))

In [337]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [338]:
arr[0]

array([0., 1., 2., 3.])

In [339]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [340]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [341]:
series = frame.iloc[0]

In [342]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [343]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [344]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [345]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [346]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [347]:
series2

b    0
e    1
f    2
dtype: int64

In [348]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [349]:
series3 = frame['d']

In [350]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [351]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [352]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [353]:
frame

b         d         e
Utah    0.721522 -1.346538  0.814678
Ohio    1.823589  0.879872  0.767735
Texas   0.519406  0.126372  0.351249
Oregon -0.396313 -1.241836  1.036193

In [354]:
np.abs(frame)

b         d         e
Utah    0.721522  1.346538  0.814678
Ohio    1.823589  0.879872  0.767735
Texas   0.519406  0.126372  0.351249
Oregon  0.396313  1.241836  1.036193

In [355]:
f = lambda x: x.max() - x.min()

In [356]:
frame.apply(f)

b    2.219902
d    2.226410
e    0.684944
dtype: float64

In [357]:
frame.apply(f, axis='columns')

Utah      2.161216
Ohio      1.055854
Texas     0.393034
Oregon    2.278029
dtype: float64

In [358]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [359]:
frame.apply(f)

b         d         e
min -0.396313 -1.346538  0.351249
max  1.823589  0.879872  1.036193

In [360]:
format = lambda x: '%.2f' % x

In [361]:
frame.applymap(format)

b      d     e
Utah     0.72  -1.35  0.81
Ohio     1.82   0.88  0.77
Texas    0.52   0.13  0.35
Oregon  -0.40  -1.24  1.04

In [362]:
frame['e'].map(format)

Utah      0.81
Ohio      0.77
Texas     0.35
Oregon    1.04
Name: e, dtype: object

In [363]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [364]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [365]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=['three', 'one'],
                    columns=['d', 'a', 'b', 'c'])

In [366]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [367]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [368]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [369]:
obj = pd.Series([4, 7, -3, 2])

In [370]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [371]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [372]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [373]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [374]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [375]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [376]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [377]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [378]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [379]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [380]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [381]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})

In [382]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [383]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [384]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [385]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [386]:
obj.index.is_unique

False

In [387]:
obj['a']

a    0
a    1
dtype: int64

In [388]:
obj['c']

4

In [389]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [390]:
df

0         1         2
a -0.656402  1.283192 -0.157932
a -0.354341  0.476648  0.911491
b  0.782724  0.525976 -0.903539
b  0.966029 -1.886155  0.949560

In [391]:
df.loc['b']

0         1         2
b  0.782724  0.525976 -0.903539
b  0.966029 -1.886155  0.949560

In [392]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                 [np.nan, np.nan], [0.75, -1.3]],
                 index=['a','b','c','d'],
                 columns=['one','two'])

In [393]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [394]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [395]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [396]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [397]:
df.idxmax()

one    b
two    d
dtype: object

In [398]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [399]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [400]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [401]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [402]:
import pandas_datareader.data as web

In [403]:
all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [404]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})

In [405]:
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [406]:
returns = price.pct_change()

In [407]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-08-19  0.001255 -0.008646 -0.006067 -0.007102
2020-08-20  0.022190 -0.005572  0.023271  0.022113
2020-08-21  0.051532  0.000081 -0.007270 -0.000841
2020-08-24  0.011960  0.020461  0.003145  0.004923
2020-08-25 -0.008204 -0.008275  0.013009  0.012605

In [408]:
returns['MSFT'].corr(returns['IBM'])

0.5821320435711667

In [409]:
returns['MSFT'].cov(returns['IBM'])

0.00016175223534903912

In [410]:
returns.MSFT.corr(returns.IBM)

0.5821320435711667

In [411]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.510297  0.703913  0.657815
IBM   0.510297  1.000000  0.582132  0.535959
MSFT  0.703913  0.582132  1.000000  0.782703
GOOG  0.657815  0.535959  0.782703  1.000000

In [412]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000337  0.000150  0.000224  0.000198
IBM   0.000150  0.000257  0.000162  0.000141
MSFT  0.000224  0.000162  0.000300  0.000222
GOOG  0.000198  0.000141  0.000222  0.000269

In [413]:
returns.corrwith(returns.IBM)

AAPL    0.510297
IBM     1.000000
MSFT    0.582132
GOOG    0.535959
dtype: float64

In [414]:
returns.corrwith(volume)

AAPL   -0.086653
IBM    -0.099863
MSFT   -0.051246
GOOG   -0.154407
dtype: float64

In [415]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [416]:
uniques = obj.unique()

In [417]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [418]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [419]:
pd.value_counts(obj.values, sort=False)

d    1
a    3
c    3
b    2
dtype: int64

In [420]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [421]:
mask = obj.isin(['b', 'c'])

In [422]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [423]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [424]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [425]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [426]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [427]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                    'Qui2': [2, 3, 1, 2, 3],
                    'Qui3': [1, 5, 2, 4, 4]})

In [428]:
data

Qu1  Qui2  Qui3
0    1     2     1
1    3     3     5
2    4     1     2
3    3     2     4
4    4     3     4

In [429]:
result = data.apply(pd.value_counts).fillna(0)

In [430]:
result

Qu1  Qui2  Qui3
1  1.0   1.0   1.0
2  0.0   2.0   1.0
3  2.0   2.0   0.0
4  2.0   0.0   2.0
5  0.0   0.0   1.0